[package]
name = "ftool-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.40", features = ["derive"] }
dotenv = "0.15.0"
log = "0.4.27"
rusty_falcon = "0.4.0"
tokio = {version = "1.45.1", features = ["full"]}
env_logger = "0.11.8"
fern = "0.7.1"
chrono = "0.4.41"
